### ISSUE TITLE
合并转发私聊图片会失效，但我发现了咋修复，虽然不懂为什么

### ISSUE THREAD

**Issue by islanddddddd** [Admsec/kivibot-plugin-msgrecall#2]
### 电脑打开转圈，手机显示已清理或者过期。

![image](https://user-images.githubusercontent.com/38216943/213543839-75a157ad-81a7-4416-b014-ce9bac976674.png)

![E7B84BB6EE0DF3B6FAE22C77B5EA6CB7](https://user-images.githubusercontent.com/38216943/213544130-102ef02d-cac1-4b42-a352-abd5341642fb.jpg)

### 然后查看ociq的issue

发现了有人遇到过类似的takayama-lily/oicq#226

### 查看文档发现有个dm参数

![image](https://user-images.githubusercontent.com/38216943/213545519-3a765afd-e393-4ca9-804b-6f201669fea0.png)

### 我把dm改为true就可以正常显示了，但我并没找到dm的解释

![image](https://user-images.githubusercontent.com/38216943/213546027-03d0d75b-027e-4a8e-a8ab-fb0c61fc8ffd.png)

**Comment by islanddddddd** [comment]
![image](https://user-images.githubusercontent.com/38216943/213546377-5f5a86ac-b16b-408c-9728-428b8bb78752.png)
就是这个

**Comment by islanddddddd** [comment]
### 我给它再删了
![image](https://user-images.githubusercontent.com/38216943/213546915-41f58b5c-ce3b-4909-9418-e4b620e62f1f.png)
###  测试
![image](https://user-images.githubusercontent.com/38216943/213546936-f632f743-8544-48fb-9cae-7bd0643d82ae.png)
### 确实有问题
![image](https://user-images.githubusercontent.com/38216943/213546999-ef2a43ec-9495-4332-bee2-f5429de97143.png)

**Comment by Admsec** [comment]
dm 我也不知道是什么意思，不过这样能修好的话就先按照这样修吧

**Comment by Admsec** [comment]
已将 dm 改为 true
